backend:
  name: github
  repo: for-sport/workspace
  branch: main
  base_url: https://fs-whats-on.netlify.app
  auth_endpoint: oauth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "greeting"
    label: "Greeting"
    folder: "apps/whats-on/src/content/greeting"
    create: false
    fields:
      - { label: "Text", name: "text", widget: "string" }

  - name: "movies"
    label: "Movies"
    folder: "apps/whats-on/src/content/movies"
    create: true
    fields:
      - { label: "Movie List", name: "movies", widget: "text" }
